from PyQt5 import QtCore, QtGui, QtWidgets
import pyqtgraph as pg

class Ui_MainWindow(QtWidgets.QWidget):
    import sys
    def __init__(self, parent=None):
        super(Ui_MainWindow, self).__init__(parent)
        self.setupUi(self)
        
    def setupUi(self, MainWindow):
        #This is all just drawing the GUI and setting things in place
        MainWindow.setObjectName("PI-ICR Analysis")
        MainWindow.resize(1500, 1000)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.refClusterSelect = QtWidgets.QComboBox(self.centralWidget)
        self.refClusterSelect.setGeometry(QtCore.QRect(20, 540, 500, 22))
        self.refClusterSelect.setObjectName("refClusterSelect")
        self.measClusterSelect = QtWidgets.QComboBox(self.centralWidget)
        self.measClusterSelect.setGeometry(QtCore.QRect(680, 540, 500, 22))
        self.measClusterSelect.setObjectName("measClusterSelect")
        self.refPhi = QtWidgets.QLineEdit(self.centralWidget)
        self.refPhi.setGeometry(QtCore.QRect(220, 570, 200, 20))
        self.refPhi.setObjectName("refPhi")
        self.measPhi = QtWidgets.QLineEdit(self.centralWidget)
        self.measPhi.setGeometry(QtCore.QRect(880, 570, 200, 20))
        self.measPhi.setObjectName("measPhi")
        self.label = QtWidgets.QLabel(self.centralWidget)
        self.label.setGeometry(QtCore.QRect(100, 570, 71, 20))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralWidget)
        self.label_2.setGeometry(QtCore.QRect(760, 570, 71, 20))
        self.label_2.setObjectName("label_2")
        self.refRadius = QtWidgets.QLineEdit(self.centralWidget)
        self.refRadius.setGeometry(QtCore.QRect(220, 600, 200, 20))
        self.refRadius.setObjectName("refRadius")
        self.measRadius = QtWidgets.QLineEdit(self.centralWidget)
        self.measRadius.setGeometry(QtCore.QRect(880, 600, 200, 20))
        self.measRadius.setObjectName("measRadius")
        self.label_3 = QtWidgets.QLabel(self.centralWidget)
        self.label_3.setGeometry(QtCore.QRect(100, 600, 71, 20))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralWidget)
        self.label_4.setGeometry(QtCore.QRect(760, 600, 71, 20))
        self.label_4.setObjectName("label_4")
        self.Theta = QtWidgets.QLineEdit(self.centralWidget)
        self.Theta.setGeometry(QtCore.QRect(650, 630, 200, 20))
        self.Theta.setObjectName("Theta")
        self.N = QtWidgets.QLineEdit(self.centralWidget)
        self.N.setGeometry(QtCore.QRect(650, 660, 200, 20))
        self.N.setObjectName("N")
        self.Frequency = QtWidgets.QLineEdit(self.centralWidget)
        self.Frequency.setGeometry(QtCore.QRect(650, 690, 200, 20))
        self.Frequency.setObjectName("Frequency")
        self.label_5 = QtWidgets.QLabel(self.centralWidget)
        self.label_5.setGeometry(QtCore.QRect(530, 630, 71, 20))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralWidget)
        self.label_6.setGeometry(QtCore.QRect(530, 660, 71, 20))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralWidget)
        self.label_7.setGeometry(QtCore.QRect(530, 690, 71, 20))
        self.label_7.setObjectName("label_7")
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1500, 21))
        self.menuBar.setObjectName("menuBar")
        fileMenu = self.menuBar.addMenu('&File')
        infoMenu = self.menuBar.addMenu('&Info')
        pg.setConfigOption('background', 'w')
        pg.setConfigOption('foreground', 'k')
        self.refGraph = pg.PlotWidget(self.centralWidget)
        self.refGraph.setObjectName("refGraph")
        self.refGraph.setGeometry(QtCore.QRect(20, 30, 500, 500))
        self.measGraph = pg.PlotWidget(self.centralWidget)
        self.measGraph.setObjectName("measGraph")
        self.measGraph.setGeometry(QtCore.QRect(680, 30, 500, 500))
        self.EnterButton = QtWidgets.QPushButton(self.centralWidget)
        self.EnterButton.setGeometry(450, 640, 60, 60)
        self.EnterButton.setDefault(False)
        self.EnterButton.setFlat(False)
        self.EnterButton.setObjectName("EnterButton")
        self.EnterButton.setText("Calculate")
        self.Species = QtWidgets.QLabel(self.centralWidget)
        self.Species.move(570, 30)
        self.Species.setObjectName("Species")
        self.Species.setStyleSheet("font:30pt")
        self.actionLoad_New_Reference = fileMenu.addAction("Load New Reference")
        self.actionLoad_New_Measurement = fileMenu.addAction("Load New Measurement")
        self.actionExit = fileMenu.addAction("Exit")
        self.actionCalibrate = infoMenu.addAction("Calibration")
        self.actionMeasurement = infoMenu.addAction("Measurement")

        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.retranslateUi(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "PI-ICR Analysis"))
        self.label.setText(_translate("MainWindow", "Angle"))
        self.label_2.setText(_translate("MainWindow", "Angle"))
        self.label_3.setText(_translate("MainWindow", "Radius"))
        self.label_4.setText(_translate("MainWindow", "Radius"))
        self.label_5.setText(_translate("MainWindow", "Theta"))
        self.label_6.setText(_translate("MainWindow", "N"))
        self.label_7.setText(_translate("MainWindow", "Frequency"))
        self.actionLoad_New_Reference.setText(_translate("MainWindow", "Load New Reference"))
        self.actionLoad_New_Measurement.setText(_translate("MainWindow", "Load New Measurement"))
